services:
  # ==========================================
  # 1. Message Broker (Kafka API compatible)
  # ==========================================
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --mode dev-container
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - "19092:19092"
      - "9092:9092"
      - "8082:8082"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  # UI xem topic & messages trên trình duyệt
  redpanda-console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    restart: on-failure
    depends_on:
      - redpanda
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: "redpanda:9092"

  # ==========================================
  # 2. Airflow Metadata Database
  # ==========================================
  postgres-airflow:
    image: postgres:15-alpine
    container_name: postgres-airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow_password
      POSTGRES_DB: airflow
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # ==========================================
  # 3. Airflow Scheduler & Webserver
  # ==========================================
  airflow-webserver:
    image: apache/airflow:2.8.1-python3.10
    container_name: airflow-webserver
    restart: always
    depends_on:
      - postgres-airflow
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow_password@postgres-airflow/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/keys/gcp_key.json
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/keys:/opt/airflow/keys:ro
      - ./streaming/delta_lake:/opt/airflow/delta_lake:ro
    ports:
      - "8085:8080"
    command: bash -c "pip install --no-cache-dir google-cloud-bigquery deltalake pandas pyarrow && airflow db migrate && airflow users create --username admin --firstname Anthony --lastname User --role Admin --email admin@example.com --password admin || true && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.8.1-python3.10
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow_password@postgres-airflow/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/keys/gcp_key.json
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/keys:/opt/airflow/keys:ro
      - ./streaming/delta_lake:/opt/airflow/delta_lake:ro
    command: bash -c "pip install --no-cache-dir google-cloud-bigquery deltalake pandas pyarrow && airflow scheduler"
    
  # ==========================================
  # 4. Spark Structured Streaming Container
  # ==========================================
  spark-streaming:
    build:
      context: ./streaming
      dockerfile: Dockerfile
    container_name: spark-streaming
    user: "0:0"
    restart: on-failure
    depends_on:
      - redpanda
    environment:
      - KAFKA_BROKER=redpanda:9092
    volumes:
      - ./streaming:/opt/spark-apps
    working_dir: /opt/spark-apps
    command: >
      spark-submit
      --conf spark.jars.ivy=/tmp/.ivy2
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,io.delta:delta-spark_2.12:3.1.0
      spark_streaming.py
volumes:
  redpanda_data:
  postgres_airflow_data: